#!/usr/bin/env python3
'''Call linters for all files and format output.'''

import re
import os
import subprocess
import argparse


def lintfile(filename):
    shellre = re.compile('^#! *\/bin\/(a|ba)?sh$')
    with open(filename, 'r') as fd:
        try:
            firstline = fd.readline()
        except UnicodeDecodeError:
            firstline = ''
        ext = os.path.splitext(filename)[1]
        if shellre.match(firstline):
            subprocess.call(['shellcheck', filename])
            return
        elif ext == '.py':
            subprocess.call(['flake8', filename])
            subprocess.call(['py3kwarn', filename])
            return


def lintdir(dirname):
    exclude = set(['.git', 'CVS', '.svn'])
    for root, dirs, files in os.walk(dirname, topdown=True):
        dirs[:] = [d for d in dirs if d not in exclude]
        for basename in files:
            filename = os.path.join(root, basename)
            lintfile(filename)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('paths', nargs='+')
    args = parser.parse_args()
    for path in args.paths:
        lintdir(path)


if __name__ == '__main__':
    main()
