#!/usr/bin/env python3
'''Call linters for all files and format output.'''

import os
import sys
import argparse

import omnilint
from omnilint.reporters import ReporterLine


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        '--output',
        '-o',
        type=argparse.FileType('w'),
        default=sys.stderr)
    parser.add_argument('paths', nargs='+')
    args = parser.parse_args()
    ol = omnilint.Omnilint()
    ol.checkers_load()
    exclude = set(['.git', 'CVS', '.svn'])
    reporter = ReporterLine(args.output)
    for path in args.paths:
        for root, dirs, files in os.walk(path, topdown=True):
            dirs[:] = [d for d in dirs if d not in exclude]
            for basename in files:
                filename = os.path.join(root, basename)
                ol.analyse_file(reporter, filename)
    if reporter.num_errors > 0:
        sys.exit(1)


if __name__ == '__main__':
    main()
