[package]
name = "omnilint"
description = "Statically analyse any file with the appropriate tools"
version = "0.7.0"
edition = "2024"
authors = ["Leandro Lisboa Penz <lpenz@lpenz.org>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/lpenz/omnilint"
repository = "https://github.com/lpenz/omnilint"
build = "build.rs"
categories = ["command-line-utilities"]
keywords = ["command-line"]

[features]
test-linter-tools = []

[dependencies]
clap = { version = "4.6.4", features = ["derive"] }
color-eyre = "0.6.5"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1.53.1", features = ["macros", "rt", "process"] }
tokio-process-stream = "0.4"
tokio-stream = { version = "0.1.19", features = ["io-util"] }
toml = "0.8"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[build-dependencies]
clap = { version = "4.6.4", features = ["derive"] }
clap2man = "0.1.1"
clap_complete = "4.6.7"
color-eyre = "0.6.5"
man = "0.3.0"

[dev-dependencies]
assert_cmd = "2.2.2"
tempfile = "3"

[package.metadata.deb]
section = "utils"
extended-description = """\
Statically analyse any file with the appropriate tools
"""
recommends = "cppcheck, jq, libperl-critic-perl, libxml2-utils, lua-check, python3-flake8, ruff, shellcheck, sqlfluff, tidy, yamllint"
assets = [
    ["target/release/omnilint.1", "usr/share/man/man1/", "644"],
    ["target/release/omnilint", "usr/bin/", "755"],
    ["LICENSE", "usr/share/doc/omnilint/", "644"],
    ["AUTHORS", "usr/share/doc/omnilint/", "644"],
    ["README.md", "usr/share/doc/omnilint/", "644"],
    ["packaging/omnilint.toml", "etc/omnilint.toml", "644"],
    ["target/release/omnilint.bash", "/usr/share/bash-completion/completions/", "644"],
    ["target/release/_omnilint", "/usr/share/zsh/site-functions/", "644"],
    ["target/release/omnilint.fish", "/usr/share/fish/vendor_completions.d/", "644"],
]

[package.metadata.generate-rpm]
assets = [
    { source = "target/release/omnilint.1", dest = "/usr/share/man/man1/", mode = "644" },
    { source = "target/release/omnilint", dest = "/usr/bin/", mode = "755" },
    { source = "LICENSE", dest = "/usr/share/doc/omnilint/", mode = "644" },
    { source = "AUTHORS", dest = "/usr/share/doc/omnilint/", mode = "644" },
    { source = "README.md", dest = "/usr/share/doc/omnilint/", mode = "644" },
    { source = "packaging/omnilint.toml", dest = "/etc/omnilint.toml", mode = "644" },
    { source = "target/release/omnilint.bash", dest = "/usr/share/bash-completion/completions/", mode = "644" },
    { source = "target/release/_omnilint", dest = "/usr/share/zsh/site-functions/", mode = "644" },
    { source = "target/release/omnilint.fish", dest = "/usr/share/fish/vendor_completions.d/", mode = "644" },
]

[package.metadata.generate-rpm.recommends]
cppcheck = ""
jq = ""
luacheck = ""
perl-perlcritic = ""
python3-flake8 = ""
python3-sqlfluff = ""
python3-yamllint = ""
ruff = ""
ShellCheck = ""
tidy-html5 = ""
libxml2 = ""
