# syntax=docker/dockerfile:1

# Build omnilint together with all the supported linters pinned by the nix
# flake of this repository (the nixpkgs revision is pinned by flake.lock),
# and distribute just the resulting /nix/store closure in a small runtime
# image.

# ---------------------------------------------------------------- builder --
# Build the omnilint flake package and stage the store closure of the
# result for the runtime stage.
FROM docker.io/nixos/nix:2.34.8 AS builder

# The flake packages the whole repository as its source (src = ./.),
# so the whole build context is the nix source.
COPY . /src
WORKDIR /src

# Substitute store paths from the caches instead of building well-known
# derivations from scratch: the lpenz cache stores every derivation of
# this flake, and the pinned nixpkgs is served by cache.nixos.org.
RUN nix \
    --extra-experimental-features "nix-command flakes" \
    --option sandbox false \
    # filter-syscalls installs a seccomp BPF filter that cannot be loaded
    # when building aarch64-linux under QEMU emulation
    --option filter-syscalls false \
    --option substituters "https://cache.nixos.org https://lpenz.cachix.org" \
    --option trusted-public-keys "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= lpenz.cachix.org-1:ZRfvZ7o/oNiBcD9EtGKpzZSgJKG89uFZn/36zbCh1Oo=" \
    build .#default -o /result && \
    # Dereference the wrapper generated by the flake into a standalone
    # executable for the runtime stage: it sets the OMNILINT_CONFIG
    # environment variable and execs the real binary in the store.
    mkdir -p /usr/local-staging/bin /nix-layer/store && \
    install -Dm755 -t /usr/local-staging/bin /result/bin/omnilint && \
    # Stage the closure of the built package (omnilint, the generated
    # configuration and every supported linter) as a tree mirroring
    # the shape of /nix/store.
    for path in $(nix-store --query --requisites "$(readlink -f /result)"); do \
        cp -a "$path" /nix-layer/store/; \
    done

# ---------------------------------------------------------------- runtime --
# Minimal runtime image containing the nix store closure built above. A
# regular base is used instead of scratch so that /bin/sh, DNS and CA
# certificates are available to the linters.
FROM docker.io/library/alpine:3.24.1

# git runs `omnilint repository` (git ls-files) and ca-certificates gives
# linters trusted network access; everything else comes from the store.
# hadolint ignore=DL3018
RUN apk add --no-cache ca-certificates git

COPY --from=builder /nix-layer /nix
COPY --from=builder /usr/local-staging/ /usr/local/

ENV LANG=C.UTF-8 \
    LC_ALL=C.UTF-8

WORKDIR /workspace

LABEL org.opencontainers.image.title="omnilint" \
      org.opencontainers.image.description="Statically analyse any file with the appropriate tools" \
      org.opencontainers.image.source="https://github.com/lpenz/omnilint"

ENTRYPOINT ["/usr/local/bin/omnilint"]
CMD ["--help"]
