{
  description = "omnilint development environment";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

  outputs = { self, nixpkgs }:
    let
      systems = [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ];
      version = (builtins.fromTOML (builtins.readFile ./Cargo.toml)).package.version;
    in
    {
      packages = nixpkgs.lib.genAttrs systems (system:
        let
          pkgs = import nixpkgs { inherit system; };
          pyPkgs = pkgs.python3.withPackages (ps: [ ps.flake8 ps.mypy ps.pylint ]);
          # The key is the executable name that omnilint uses to look up the
          # linter; for go-vet it differs from the linter name (go).
          linterBins = [
            { key = "actionlint"; path = "${pkgs.actionlint}/bin/actionlint"; }
            { key = "bash"; path = "${pkgs.bash}/bin/bash"; }
            { key = "chktex"; path = "${pkgs.texlive.bin.chktex}/bin/chktex"; }
            { key = "clj-kondo"; path = "${pkgs.clj-kondo}/bin/clj-kondo"; }
            { key = "cppcheck"; path = "${pkgs.cppcheck}/bin/cppcheck"; }
            { key = "eslint"; path = "${pkgs.eslint}/bin/eslint"; }
            { key = "flake8"; path = "${pyPkgs}/bin/flake8"; }
            { key = "go"; path = "${pkgs.go}/bin/go"; }
            { key = "hadolint"; path = "${pkgs.hadolint}/bin/hadolint"; }
            { key = "jq"; path = "${pkgs.jq}/bin/jq"; }
            { key = "ktlint"; path = "${pkgs.ktlint}/bin/ktlint"; }
            { key = "luac"; path = "${pkgs.lua}/bin/luac"; }
            { key = "luacheck"; path = "${pkgs.luaPackages.luacheck}/bin/luacheck"; }
            { key = "luau-analyze"; path = "${pkgs.luau}/bin/luau-analyze"; }
            { key = "markdownlint-cli2"; path = "${pkgs.markdownlint-cli2}/bin/markdownlint-cli2"; }
            { key = "mypy"; path = "${pyPkgs}/bin/mypy"; }
            { key = "nix-instantiate"; path = "${pkgs.nix}/bin/nix-instantiate"; }
            { key = "oxlint"; path = "${pkgs.oxlint}/bin/oxlint"; }
            { key = "perlcritic"; path = "${pkgs.perlPackages.PerlCritic}/bin/perlcritic"; }
            { key = "protolint"; path = "${pkgs.protolint}/bin/protolint"; }
            { key = "py_compile"; path = "${pkgs.python3}/bin/python3"; }
            { key = "pylint"; path = "${pyPkgs}/bin/pylint"; }
            { key = "pyright"; path = "${pkgs.pyright}/bin/pyright"; }
            { key = "ruff"; path = "${pkgs.ruff}/bin/ruff"; }
            { key = "rubocop"; path = "${pkgs.rubocop}/bin/rubocop"; }
            { key = "shellcheck"; path = "${pkgs.shellcheck}/bin/shellcheck"; }
            { key = "sqlfluff"; path = "${pkgs.sqlfluff}/bin/sqlfluff"; }
            { key = "statix"; path = "${pkgs.statix}/bin/statix"; }
            { key = "staticcheck"; path = "${pkgs.go-tools}/bin/staticcheck"; }
            { key = "stylelint"; path = "${pkgs.stylelint}/bin/stylelint"; }
            { key = "swiftlint"; path = "${pkgs.swiftlint}/bin/swiftlint"; }
            { key = "tidy"; path = "${pkgs.html-tidy}/bin/tidy"; }
            { key = "xmllint"; path = "${pkgs.libxml2}/bin/xmllint"; }
            { key = "yamllint"; path = "${pkgs.yamllint}/bin/yamllint"; }
            { key = "zsh"; path = "${pkgs.zsh}/bin/zsh"; }
          ];
          tomlLinter = linter: "[linters.${linter.key}]\npath = \"${linter.path}\"\n";
          omnilint = pkgs.rustPlatform.buildRustPackage {
            inherit version;
            pname = "omnilint";
            src = ./.;
            cargoLock.lockFile = ./Cargo.lock;
          };
          configText =
            "# omnilint configuration generated by flake.nix.\n"
            + "# It contains the nix store path of every linter.\n\n"
            + "[global]\n"
            + "default_linter_mode = \"required\"\n\n"
            + builtins.concatStringsSep "\n" (map tomlLinter linterBins);
          omnilint-config = pkgs.writeText "omnilint.toml" configText // {
            passthru.text = configText;
          };
        in
        {
          inherit omnilint omnilint-config;
          default = pkgs.writeShellScriptBin "omnilint" ''
            export OMNILINT_CONFIG="${omnilint-config}"
            exec "${omnilint}/bin/omnilint" "$@"
          '';
        });
      devShells = nixpkgs.lib.genAttrs systems (system:
        let
          pkgs = import nixpkgs { inherit system; };
        in
        {
          default = pkgs.mkShell {
            packages = with pkgs; [
              ruff
              shellcheck
              yamllint
              actionlint
              luaPackages.luacheck
              luau
              perlPackages.PerlCritic
              clj-kondo
              hadolint
              ktlint
              swiftlint
              sqlfluff
              statix
              stylelint
              markdownlint-cli2
              libxml2
              html-tidy
              jq
              cppcheck
              go
              go-tools
              oxlint
              eslint
              pyright
              nix
              protolint
              systemd
              rubocop
              texlive.bin.chktex
              (python3.withPackages (ps: [ ps.flake8 ps.pylint ps.mypy ]))
              zsh
            ];
          };
        });
    };
}
