---
name: CI
on: [workflow_dispatch, push, pull_request]  # yamllint disable-line rule:truthy
jobs:
  # We can't run omnilint in omnilint because the dirty test files
  # have lint errors by design
  # omnilint:
  #   uses: lpenz/omnilint/.github/workflows/omnilint.yml@v0.6.0
  rust-test:
    uses: lpenz/ghworkflow-rust/.github/workflows/rust-test.yml@v0.30.0
    with:
      enable_cargo-semver-checks: false
      test_features: '[""]'
      coveralls: true
      deb: true
      rpm: true
  nix-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: cachix/install-nix-action@v31.11.1
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Run the nix-flake test script
        run: ./test-nix.sh
  commit-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
      - uses: commit-check/commit-check-action@v2.15.0
        with:
          branch: false
  rust-deploy:
    needs: [rust-test, nix-flake, commit-check]
    uses: lpenz/ghworkflow-rust/.github/workflows/rust-deploy.yml@v0.30.0
    with:
      deb: true
      rpm: true
      release_files: |
        omnilint omnilint.1
      publish_cratesio: true
      publish_github_release: true
      publish_packagecloud_repository_deb: |
        ["debian/debian/trixie",
         "debian/debian/forky",
         "ubuntu/ubuntu/resolute"]
      publish_packagecloud_repository_rpm: |
        ["rpm/rpm_any/rpm_any"]
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
